version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: se1dhe_bot
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: python -m bot.main
    volumes:
      - .:/app
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  admin:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    command: uvicorn admin.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  # Для инициализации базы данных и миграций
  alembic:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "alembic upgrade head"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
  media_data: